In [2]:
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [3]:
# data = np.loadtxt('cricket_data.txt',delimiter = ',',usecols=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
# # y = np.loadtxt('ex1data1.txt',delimiter=",",usecols=(1,))
# m = len(data)
# data1 = np.hstack((data,np.ones((m,1))))
# #np.savetxt("ex1data2.txt", data1,fmt="%2.5f")
# X = np.loadtxt('ex1data2.txt',usecols=[19,0,10,11])
# y = np.loadtxt('ex1data2.txt',usecols=[18])
# print(X)

In [4]:
X = np.loadtxt('ten_over.txt',usecols=[4,0,1,2])
y = np.loadtxt('ten_over.txt',usecols=[3])
print(X,len(X))

[[  1. 220.  72.   4.]
 [  1. 159.  83.   1.]
 [  1. 213. 108.   2.]
 ...
 [  1. 154.  89.   1.]
 [  1. 206.  57.   2.]
 [  1. 175. 101.   3.]] 2269


In [5]:
from sklearn.linear_model import LogisticRegression

In [6]:
logisticRegr = LogisticRegression()

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [8]:
x_train

array([[  1., 108.,  46.,   4.],
       [  1., 214.,  56.,   7.],
       [  1., 189., 101.,   1.],
       ...,
       [  1., 195.,  67.,   4.],
       [  1., 184.,  79.,   3.],
       [  1., 177.,  64.,   4.]])

In [9]:
y_train

array([1., 0., 0., ..., 0., 1., 0.])

In [10]:
logisticRegr.fit(x_train,y_train)

C:\Users\Prasnil\pythonAnaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [11]:
y_pred = logisticRegr.predict(x_test)
print(y_pred)
print(y_test)

[1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 0.
 1. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1.
 1. 1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0.
 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1.
 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0. 1.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 0. 0. 1. 0. 1. 1. 1.
 0. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1.
 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0. 1.
 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1.
 1. 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 0. 0. 1. 1. 1. 0. 0. 1. 1.
 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0.
 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 0.
 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1.

In [12]:
x_test

array([[  1., 167.,  68.,   2.],
       [  1., 209.,  72.,   3.],
       [  1., 167.,  68.,   2.],
       ...,
       [  1., 151.,  75.,   4.],
       [  1., 175., 101.,   3.],
       [  1., 108.,  46.,   4.]])

In [13]:
y_test

array([0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1.,
       1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0.,
       1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0.,
       1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0.,
       1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1.,
       0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 1., 1., 1., 1.

In [14]:
targets = np.array([[1,200,104,2]])
logisticRegr.predict(targets)

array([1.])

In [15]:
score = logisticRegr.score(x_test, y_test)
print(score)

0.8415492957746479


In [16]:
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[248  50]
 [ 40 230]]


In [17]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.86      0.83      0.85       298
         1.0       0.82      0.85      0.84       270

    accuracy                           0.84       568
   macro avg       0.84      0.84      0.84       568
weighted avg       0.84      0.84      0.84       568



In [18]:
parameters = logisticRegr.coef_

In [19]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt
logit_roc_auc = roc_auc_score(y_test, logisticRegr.predict(x_test))
fpr, tpr, thresholds = roc_curve(y_test, logisticRegr.predict_proba(x_test)[:,1])
plt.figure()
plt.plot(fpr, tpr, label='Logistic Regression (area = %0.2f)' % logit_roc_auc)
plt.plot([0, 1], [0, 1],'r--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic')
plt.legend(loc="lower right")
plt.savefig('Log_ROC')
plt.show()

<Figure size 640x480 with 1 Axes>

In [20]:
print(parameters)

[[ 5.12953837 -0.07042729  0.06209219 -1.16421912]]


In [21]:
# th = np.array([0.13640112,-0.09403004,0.04075078,0.13683161,-0.36898452])
# print(th.shape)

In [22]:
# targets = np.array([1,200,149,50,6])
# print(targets.shape)

In [23]:
# val= targets@th
# val

In [24]:
# print(round(float(Sigmoid(targets@th)),3))

In [25]:
np.array([1,2,3])@np.array([1, 2, 3])

14

In [26]:
a = np.array([1,2,3])

In [27]:
a.shape

(3,)